field: f58fb43d-8b50-400c-849d-2733999229bc # Highlight Slider Cards
fieldLayouts:
  3b9666d2-b54c-4d41-ad46-2c916ce102d5:
    tabs:
      -
        elements:
          -
            fieldUid: ded4ca61-4350-4a11-9d8e-52fd27ba7372 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e8413c94-2573-4d80-96a8-d45186bed72b # Link To
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  ded4ca61-4350-4a11-9d8e-52fd27ba7372: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Override Asset Title'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
  e8413c94-2573-4d80-96a8-d45186bed72b: # Link To
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkTo
    instructions: ''
    name: 'Link To'
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds: null
      defaultUploadLocationSource: 'volume:4a17a3e8-cb94-4577-a936-853eea7c543f' # Uploads
      defaultUploadLocationSubpath: ''
      limit: '1'
      localizeRelations: false
      previewMode: full
      restrictFiles: ''
      selectionLabel: ''
      showSiteMenu: true
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:4a17a3e8-cb94-4577-a936-853eea7c543f' # Uploads
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: false
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: asset
name: Asset
sortOrder: 2
