field: f58fb43d-8b50-400c-849d-2733999229bc # Highlight Slider Cards
fieldLayouts:
  6135533b-2a7e-4a3a-bc06-b801ec8e25a3:
    tabs:
      -
        elements:
          -
            fieldUid: da1c08d3-09b3-4230-93d7-e6f88e41121a # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 21a95ca4-5a37-4fea-9ce3-bea8522e8fec # Link To
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  21a95ca4-5a37-4fea-9ce3-bea8522e8fec: # Link To
    columnSuffix: null
    contentColumnType: string
    fieldGroup: null
    handle: linkTo
    instructions: ''
    name: 'Link To'
    searchable: false
    settings:
      allowSelfRelations: false
      limit: '1'
      localizeRelations: false
      selectionLabel: ''
      showSiteMenu: true
      source: null
      sources:
        - 'section:1a373dd5-7fa7-4369-b754-1718ee61b3e3'
        - 'section:fa00de3c-a4b0-4a3e-b590-4fcd1f10deaf'
        - 'section:e5fba7f8-fb2c-4a6e-882a-6466032b9b1a'
        - 'section:308ee720-b1f6-43a2-9876-f0521de2ef39'
      targetSiteId: null
      validateRelatedElements: false
      viewMode: null
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Entries
  da1c08d3-09b3-4230-93d7-e6f88e41121a: # Heading
    columnSuffix: null
    contentColumnType: text
    fieldGroup: null
    handle: heading
    instructions: 'Override Entry Title'
    name: Heading
    searchable: false
    settings:
      byteLimit: null
      charLimit: null
      code: ''
      columnType: null
      initialRows: '4'
      multiline: ''
      placeholder: null
      uiMode: normal
    translationKeyFormat: null
    translationMethod: none
    type: craft\fields\PlainText
handle: entry
name: Entry
sortOrder: 1
