handle: rightMenuItems
instructions: 'Links that display on the right of the header.'
maxNodes: '2'
name: 'Right Menu Items'
permissions:
  craft\elements\Asset:
    enabled: '1'
    permissions: '*'
  craft\elements\Category:
    enabled: '1'
    permissions: '*'
  craft\elements\Entry:
    enabled: '1'
    permissions: '*'
  craft\elements\Tag:
    enabled: ''
    permissions: '*'
  custom:
    enabled: '1'
  verbb\navigation\nodetypes\PassiveType:
    enabled: '1'
propagateNodes: false
siteSettings:
  80b8d62b-af42-4ac6-ad7f-087f1758cb16: null # starter-project
sortOrder: 5
structure:
  maxLevels: '1'
  uid: 33be544a-97f7-4630-8a94-73fc23dc65ba
