childBlocks: ''
field: 473a3564-9521-4cf5-a436-5a6181745ffb # Billboard
fieldLayouts:
  14b55df3-8520-4414-b39d-0412d64d2868:
    tabs:
      -
        elements:
          -
            fieldUid: efe674ae-c86e-42f6-990a-d989f4755423 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48771a17-3222-416e-8842-da160b110b13 # Heading Br
            instructions: ''
            label: Heading
            required: ''
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b48c80c1-1ad6-4af5-93a8-de0935abee4e # Plain Text Br
            instructions: ''
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: billboard
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Billboard
sortOrder: 1
topLevel: true
