childBlocks: ''
field: e5faf6ba-1975-4ca3-a8c4-c939da9cd368 # Billboard Heading Copy
fieldLayouts:
  00ea2e60-dd8a-4774-9d12-5c2fc3920de8:
    tabs:
      -
        elements:
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b48c80c1-1ad6-4af5-93a8-de0935abee4e # Plain Text Br
            instructions: ''
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: billboardHeadingCopy
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Billboard Heading Copy'
sortOrder: 1
topLevel: true
