childBlocks: ''
field: 17521a95-4e4a-4d5f-9ffb-604d7f7b0858 # Billboard Investigation Reporting
fieldLayouts:
  f967c659-7644-4a9a-b5dc-913c0d3485ae:
    tabs:
      -
        elements:
          -
            fieldUid: 0d19be36-0fb7-4549-9165-ea6427c797da # Investigation Reporting Entry
            instructions: ''
            label: 'Investigation/Reporting Entry'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 00e8ad18-40de-4f16-99f6-ad27a14f73ae # Image/Video
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: billboardInvestigationReporting
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Billboard
sortOrder: 1
topLevel: true
