childBlocks: null
field: 7f23176c-a8df-4d34-b601-96f076686723 # Page Builder - Reporting
fieldLayouts:
  13ce031a-c8fa-4681-be32-3042f6b5b931:
    tabs:
      -
        elements:
          -
            fieldUid: 07c44a7a-06cd-4843-bce5-56aa56ebe7ff # Embed Code
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: misc
        sortOrder: 1
handle: embed
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Embed
sortOrder: 4
topLevel: true
