childBlocks: ''
field: 7772400f-679e-4618-bcb7-be31d722cdcd # Page Builder - Homepage
fieldLayouts:
  fdd8a43d-7c60-404d-b7fc-f9256cd406c1:
    tabs:
      -
        elements:
          -
            fieldUid: edc5edad-1d37-4f4b-a8e2-c1715aec6e08 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a9a3ca0-8c46-4200-95e3-46db296d3ce4 # Plain Text
            instructions: ''
            label: Label
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 48771a17-3222-416e-8842-da160b110b13 # Heading Br
            instructions: ''
            label: Heading
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 11eb46d0-3abc-4e72-bc53-b6c9e53d6342 # Linkit Full
            instructions: ''
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            type: craft\fieldlayoutelements\HorizontalRule
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 08b4219c-c40c-40c9-be83-f1711e1a0c40 # Entries (6)
            instructions: ''
            label: 'Other Entries'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: f58fb43d-8b50-400c-849d-2733999229bc # Highlight Slider Cards
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: highlightArticleSlider
maxBlocks: 0
maxChildBlocks: 1
maxSiblingBlocks: 0
name: 'Highlight & Article Slider'
sortOrder: 4
topLevel: true
