childBlocks: null
field: 7f23176c-a8df-4d34-b601-96f076686723 # Page Builder - Reporting
fieldLayouts:
  b8c0e702-8da0-4b6f-9cb0-df03bc837319:
    tabs:
      -
        elements:
          -
            fieldUid: efe674ae-c86e-42f6-990a-d989f4755423 # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: 38c288de-a798-422c-8899-dbf0dfb1bd91 # Full Width
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: misc
        sortOrder: 1
handle: image
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Image
sortOrder: 2
topLevel: true
