childBlocks: ''
field: 7772400f-679e-4618-bcb7-be31d722cdcd # Page Builder - Homepage
fieldLayouts:
  efff96db-96a3-45c7-9725-acb20f49dcd0:
    tabs:
      -
        elements:
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: d6392018-b576-4af9-966f-3ab86da12b16 # News (4)
            instructions: "Limit 4.\r\nIf no news is selected, the latest 4 news will be shown."
            label: News
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: inTheNews
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'In The News'
sortOrder: 2
topLevel: true
