childBlocks: ''
field: 4455bdce-11b7-488a-931e-503ec12af06a # Investigations By Category
fieldLayouts:
  514823a1-2f0f-4ff4-8e51-a3591ceb34f7:
    tabs:
      -
        elements:
          -
            fieldUid: 46a8be5e-c7d0-4f96-8600-ad90a4e02ef5 # Investigation Category
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: edc5edad-1d37-4f4b-a8e2-c1715aec6e08 # Background Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: investigationsByCategory
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Investigations By Category'
sortOrder: 1
topLevel: true
