childBlocks: ''
field: 7772400f-679e-4618-bcb7-be31d722cdcd # Page Builder - Homepage
fieldLayouts:
  64c1acd2-07bc-415a-846f-484019b13459:
    tabs:
      -
        elements:
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
          -
            fieldUid: ac03b4e8-8e0a-4b09-8044-acd34f681e5d # Number [3-5]
            instructions: 'Default 3. Range [3-5].'
            label: 'Number Of Last Investigations'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 50
        name: Content
        sortOrder: 1
handle: investigationsList
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: 'Investigations List'
sortOrder: 6
topLevel: true
