childBlocks: null
field: 7f23176c-a8df-4d34-b601-96f076686723 # Page Builder - Reporting
fieldLayouts:
  72845dda-d7c1-4d76-a0b5-5f49dc90328b:
    tabs:
      -
        elements:
          -
            fieldUid: b48c80c1-1ad6-4af5-93a8-de0935abee4e # Plain Text Br
            instructions: ''
            label: Quote
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 0a9a3ca0-8c46-4200-95e3-46db296d3ce4 # Plain Text
            instructions: ''
            label: Quotee
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: misc
        sortOrder: 1
handle: quote
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Quote
sortOrder: 3
topLevel: true
