childBlocks: null
field: 7f23176c-a8df-4d34-b601-96f076686723 # Page Builder - Reporting
fieldLayouts:
  1b906f7c-4d32-4ca2-9665-98fb411ba546:
    tabs:
      -
        elements:
          -
            fieldUid: 4cbd7fc4-da0c-460e-b563-462a8e59d1d6 # Background Color
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 99ebb67b-8df9-4d2a-8889-060a14e56a0f # Redactor Content Advanced
            instructions: ''
            label: WYSIWYG
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: redactorContentAdvanced
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: WYSIWYG
sortOrder: 1
topLevel: true
