childBlocks: ''
field: 7772400f-679e-4618-bcb7-be31d722cdcd # Page Builder - Homepage
fieldLayouts:
  1d5bb61c-6c72-4948-b6f0-61fcba72aa48:
    tabs:
      -
        elements:
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            style: tip
            tip: 'This block shows the **5 recent reportings**.'
            type: craft\fieldlayoutelements\Tip
        name: Content
        sortOrder: 1
handle: reportings
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Reportings
sortOrder: 1
topLevel: true
