childBlocks: null
field: 7f23176c-a8df-4d34-b601-96f076686723 # Page Builder - Reporting
fieldLayouts:
  cd70c7bb-85bd-4266-bd50-297c86af8acc:
    tabs:
      -
        elements:
          -
            fieldUid: 1106e99b-350f-4cf2-9455-907724cb12a0 # Heading
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: b48c80c1-1ad6-4af5-93a8-de0935abee4e # Plain Text Br
            instructions: ''
            label: Copy
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 11eb46d0-3abc-4e72-bc53-b6c9e53d6342 # Linkit Full
            instructions: ''
            label: Button
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: subscribe
maxBlocks: 0
maxChildBlocks: 0
maxSiblingBlocks: 0
name: Subscribe
sortOrder: 5
topLevel: true
