fieldLayouts:
  715dfc2d-581b-49d4-85c7-74b7affb121d:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\AssetTitleField
            warning: null
            width: 100
          -
            fieldUid: a8bfb5d5-6e60-4cb0-8cfb-f8c84d7d6077 # Credit
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: uploads
hasUrls: true
name: Uploads
settings:
  bucket: $SPACES_BUCKET
  contentDisposition: ''
  endpoint: $SPACES_ENDPOINT
  expires: ''
  keyId: $SPACES_API_KEY
  region: $SPACES_REGION
  secret: $SPACES_SECRET
  subfolder: uploads
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: null
type: vaersaagod\dospaces\Volume
url: $SPACES_URL
