columnSuffix: khuyhgyg
contentColumnType: string
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: bannerType
instructions: ''
name: 'Banner Type'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - Overlay
        -
          - value
          - overlay
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Boxed
        -
          - value
          - boxed
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
