columnSuffix: null
contentColumnType: string
fieldGroup: 596142ba-11e5-4895-bde2-e81ebfba51c9 # Content 
handle: billboardHeadingCopy
instructions: ''
name: 'Billboard Heading Copy'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: true
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
