columnSuffix: giacazry
contentColumnType: text
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: headingBr
instructions: ''
name: 'Heading Br'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '2'
  multiline: '1'
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
