columnSuffix: null
contentColumnType: string
fieldGroup: 596142ba-11e5-4895-bde2-e81ebfba51c9 # Content 
handle: pageBuilderReporting
instructions: ''
name: 'Page Builder - Reporting'
searchable: false
settings:
  maxBlocks: ''
  maxLevels: ''
  maxTopBlocks: ''
  minBlocks: ''
  propagationMethod: all
  wasModified: false
translationKeyFormat: null
translationMethod: site
type: benf\neo\Field
