columnSuffix: blsskdlz
contentColumnType: datetime
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: publishedDate
instructions: ''
name: 'Published Date'
searchable: false
settings:
  max: null
  min: null
  minuteIncrement: '30'
  showDate: true
  showTime: true
  showTimeZone: ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Date
