columnSuffix: null
contentColumnType: string
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: servicesGrid
instructions: ''
name: 'Services Grid'
searchable: false
settings:
  contentTable: '{{%matrixcontent_servicesgrid}}'
  maxBlocks: ''
  minBlocks: ''
  propagationKeyFormat: null
  propagationMethod: all
translationKeyFormat: null
translationMethod: site
type: craft\fields\Matrix
