columnSuffix: null
contentColumnType: string
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: team
instructions: ''
name: Team
searchable: false
settings:
  allowSelfRelations: false
  limit: ''
  localizeRelations: false
  selectionLabel: 'Add a team member'
  showSiteMenu: true
  source: null
  sources:
    - 'section:841fe8b0-59c4-48dd-8a30-f7d59faf83ef'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
