columnSuffix: hpcirzgt
contentColumnType: string
fieldGroup: a886dc53-7c97-4221-86c6-8066c5398d92 # Common
handle: theme
instructions: ''
name: 'Background Color'
searchable: false
settings:
  optgroups: true
  options:
    -
      __assoc__:
        -
          - label
          - None
        -
          - value
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Outlined
        -
          - value
          - outlined
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Light Blue'
        -
          - value
          - blue-light
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - 'Dark Blue'
        -
          - value
          - blue-dark
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Yellow
        -
          - value
          - yellow
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
